name: Java CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Set the desired Java version

    - name: Build with Maven
      run: mvn package

    - name: Run tests
      run: mvn test
